services:
  flight-poller:
    build: .
    container_name: flight-poller
    restart: unless-stopped
    environment:
      - RECEIVER_URL=http://10.10.30.227:8754/flights.json
      - WORKER_URL=https://flight.mason-kevinc.workers.dev
      - API_KEY=289d176c97499df7b960672cdaf33ed411a7397ce3df560fd0c18ea0d67ed256
      - POLL_MS=15000
      - NTFY_URL=https://ntfy.sh/flight-alerts-f655e44d4857d71e
