name              = "flight"
main              = "src/index.js"
compatibility_date = "2025-01-01"

[[rules]]
type      = "Text"
globs     = ["**/*.html"]
fallthrough = true

[triggers]
crons = ["*/5 * * * *"]

[[d1_databases]]
binding       = "DB"
database_name = "flight"
database_id   = "61f77d76-83cf-41f1-ae38-ef7a600cea7e"
